name: Cypress tests
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: ./
        with:
          working-directory: CypressTests/cypress/e2e
          build: npx cypress info
