name: Cypress tests
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: setup NPM package
        run: npm init -y && npm install
        
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm i -D cypress
          config-file: support/e2e.js
          spec: CypressTests/e2e/CloudResumechallenge.cy.js
  
